In [75]:
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [76]:
data = np.loadtxt('data/test-100-10.csv',skiprows=1,delimiter=',') 

In [77]:
len(data)

1000

In [78]:
data[0]

array([ 0.89593,  0.80969,  0.87827,  0.64812,  0.47133,  0.5105 ,
        0.40881,  0.76693,  0.21575,  0.44495,  6.5724 ])

In [86]:
X = np.delete(data, 10, axis=1)
y = data[:,10]

In [87]:
X[0]

array([ 0.89593,  0.80969,  0.87827,  0.64812,  0.47133,  0.5105 ,
        0.40881,  0.76693,  0.21575,  0.44495])

In [88]:
y[0]

6.5724

In [89]:
clf = linear_model.Ridge (alpha = .5)

In [90]:
clf.fit(X,y) 

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [91]:
clf.coef_

array([ 0.81290213,  0.97934245,  0.49555721,  0.43933786,  0.48757765,
        1.14719463,  0.98954155,  0.10574895,  0.29219335,  0.98296602])

In [93]:
clf.intercept_

2.1005298825409064